---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: rhel-ai-team
  name: prometheus-8x7b-v2-0-1-1-0
  namespace: rhel-ai-tenant
spec:
  releasePlan: models-1-1-prod
  snapshot: prometheus-8x7b-v2-0-1-1-0
  data:
    mapping:
      defaults:
        tags:
          - "1.1.0"
