---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: prometheus-8x7b-v2-0-1-1-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: models
  artifacts: {}
  components:
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models/prometheus-8x7b-v2-0:297eae7e820210dc70e1ab768b5e5864f1390f11
      name: prometheus-8x7b-v2-0
      source:
        git:
          revision: 297eae7e820210dc70e1ab768b5e5864f1390f11
          url: https://gitlab.com/redhat/rhel-ai/models/prometheus-8x7b-v2-0
