---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: amd-bootc-iso-disk-image-1-3-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: amd-bootc-1-3-iso-disk-image
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/amd-bootc-1-3-iso-disk-image/amd-bootc-1-3-iso-disk-image@sha256:8b881ef74e5e7708a035b20faa270ac17f0c1340b6407966b4e8c34798be1edf
    name: amd-bootc-1-3-iso-disk-image
    source:
      git:
        revision: d0f1f18cef7743ffe650744a8319e86a26b7d76c
        url: https://gitlab.com/redhat/rhel-ai/disk-images/amd-bootc
