kind: Task
apiVersion: tekton.dev/v1
metadata:
  name: configure-vm-cuda
spec:
  params:
    - name: cuda-compat-version
      default: "12-9"
    - name: host-access-secret-name
    - name: nvidia-driver-version
      default: "570"
      description: NVIDIA driver version to install, 570 for CUDA 12.8
  steps:
    - image: quay.io/konflux-ci/release-service-utils@sha256:2f9e6863e82bbc9ddce5a290f3fd0e87657c475e3de8a832b2ef7f8d0671e7d3
      env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: "$(params.host-access-secret-name)"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: "$(params.host-access-secret-name)"
      volumeMounts:
        - name: mapt-ssh-key
          mountPath: /mnt/mapt-ssh-key
        - name: shared-ssh-key
          mountPath: /mnt/shared-ssh-key
      script: |
        #!/bin/bash
        set -e
        echo -e "\n=== Preparing SSH private key ==="
        cp /mnt/mapt-ssh-key/id_rsa id_rsa
        chmod 400 id_rsa

        echo -e "\n=== ssh to the VM ${USERNAME}@${HOST} and print OS version ==="
        ssh_cmd="ssh -i id_rsa -o StrictHostKeyChecking=no ${USERNAME}@${HOST}"
        ${ssh_cmd} cat /etc/redhat-release

        echo -e "\n=== Adding shared SSH key ==="
        cat /mnt/shared-ssh-key/aipcc.pub | ${ssh_cmd} "cat >> ~/.ssh/authorized_keys"

        echo -e "\n=== lspci ==="
        ${ssh_cmd} lspci | grep -i nvidia

        echo -e "\n=== Installing Hugging Face CLI ==="
        ${ssh_cmd} sudo dnf install -y python3-pip
        ${ssh_cmd} pip install -U "huggingface_hub[cli]"
        arch=$(${ssh_cmd} uname -m)

        echo -e "\n=== Enabling rpm repositories for ${arch}"
        if [ "${arch}" = "x86_64" ]; then
          ${ssh_cmd} sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/x86_64/cuda-rhel9.repo
        else
          ${ssh_cmd} sudo dnf config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel9/sbsa/cuda-rhel9.repo
        fi
        
        ${ssh_cmd} sudo dnf config-manager --enable codeready-builder-for-rhel-9-rhui-rpms
        ${ssh_cmd} sudo dnf config-manager --add-repo https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo
        ${ssh_cmd} sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
        ${ssh_cmd} sudo dnf module enable -y nvidia-driver:$(params.nvidia-driver-version)-open # 570 for CUDA 12.8

        echo -e "\n=== Installing nvidia driver ==="
        ${ssh_cmd} sudo dnf install -y nvidia-driver-cuda kmod-nvidia-open-dkms

        echo -e "\n=== Installing cuda-compat package ==="
        ${ssh_cmd} sudo dnf install -y cuda-compat-$(params.cuda-compat-version)

        echo -e "\n=== Installing nvidia container toolkit ==="
        ${ssh_cmd} sudo dnf install -y nvidia-container-toolkit-base

        echo -e "\n=== Configuring SELinux allow device access in podman ==="
        ${ssh_cmd} sudo setsebool -P container_use_devices 1

        echo -e "\n=== Rebooting the VM ==="
        ${ssh_cmd} sudo reboot

        echo -e "\n=== Waiting for the VM to reboot ==="
        # VM restart quickly but bare metal VMs need some time to be ready
        for i in $(seq 1 20); do
          echo -e "\n=== Sleeping for 30 seconds $i/10 ==="
          sleep 30

          if ${ssh_cmd} true; then
            ${ssh_cmd} 'until systemctl is-system-running --wait >/dev/null 2>&1; do sleep 2; done'
            break
          fi
        done

        echo -e "\n=== /proc/driver/nvidia/version ==="
        ${ssh_cmd} cat /proc/driver/nvidia/version

        echo -e "\n=== nvidia-smi ==="
        ${ssh_cmd} nvidia-smi

        echo -e "\n=== Configuring Container Device Interface (CDI) ==="
        ${ssh_cmd} sudo nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml
        ${ssh_cmd} nvidia-ctk cdi list

        # "podman run" process is killed when ssh session is closed which
        # happens randomly, probably because it runs on OpenShift
        echo -e "\n=== Enabling linger for podman ==="
        ${ssh_cmd} "sudo loginctl enable-linger $USERNAME"
        ${ssh_cmd} "loginctl show-user $USERNAME | grep Linger"

  volumes:
    - name: mapt-ssh-key
      secret:
        secretName: "$(params.host-access-secret-name)"
        defaultMode: 0400
        items:
          - key: id_rsa
            path: id_rsa
            mode: 0400
    - name: shared-ssh-key
      secret:
        secretName: "shared-ssh-key"
        defaultMode: 0400
        items:
          - key: id_rsa.pub
            path: aipcc.pub
            mode: 0400