kind: Task
apiVersion: tekton.dev/v1
metadata:
  name: execute-script-on-vm
spec:
  params:
    - name: debug
      default: "false"
    - name: host-access-secret-name
    - name: script
      default: | 
        #!/bin/bash
        set -e
    - name: wait-for-connection
      description: Wait for the VM to be available before executing the script, useful after a reboot.
      default: "false"
  steps:
    - image: quay.io/konflux-ci/release-service-utils@sha256:aacaec006068dd6e8f66c9e1c4fd2556e8359d06579968c3ef5d1cd8065107bf
      env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: "$(params.host-access-secret-name)"
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: "$(params.host-access-secret-name)"
      volumeMounts:
        - name: ssh-key
          mountPath: /mnt/ssh-key
      script: |
        #!/bin/bash
        set -e

        echo -e "\n=== Preparing SSH private key ==="
        cp /mnt/ssh-key/id_rsa id_rsa
        chmod 400 id_rsa

        HOST=$(echo "${HOST}" | tr -d '\n\r')
        USERNAME=$(echo "${USERNAME}" | tr -d '\n\r')

        ssh_cmd="ssh -i id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o BatchMode=yes -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -o ConnectTimeout=10 ${USERNAME}@${HOST}"

        if [[ "$(params.wait-for-connection)" == "true" ]]; then
          echo -e "\n=== Waiting for the VM to be available ==="
          # VM restart quickly but bare metal VMs need some time to be ready
          for i in $(seq 1 20); do
            if ${ssh_cmd} true >/dev/null 2>&1; then
              ${ssh_cmd} "until systemctl is-system-running --wait >/dev/null 2>&1; do sleep 2; done"
              break
            fi

            echo -e "\n=== System is not ready, sleeping for 30 seconds $i/10 ==="
            sleep 30
          done
        fi

        echo -e "\n=== Executing script on VM ==="
        ${ssh_cmd} '$(params.script)'

  volumes:
    - name: ssh-key
      secret:
        secretName: "$(params.host-access-secret-name)"
        items:
          - key: id_rsa
            path: id_rsa
