---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: models-1-2-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: models-1-2
  artifacts: {}
  components:
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/granite-7b-redhat-lab-1-2@sha256:a73c41d021b0cb79b345d5b5d4444b4e4d36f6825b7aa33e4e17018807935305
      name: granite-7b-redhat-lab-1-2
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: e200b3f5bd9e621665f5e14cff8176cdb45ecf25
          url: https://gitlab.com/redhat/rhel-ai/models/granite-7b-redhat-lab
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/granite-7b-starter-1-2@sha256:44910a6a1a5325738f5c0db092805f73191f7b0c269eb5c4f8702043449d6faf
      name: granite-7b-starter-1-2
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: cfb27fd84f04f87d558c62aa2aa02e1547173ca3
          url: https://gitlab.com/redhat/rhel-ai/models/granite-7b-starter
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/granite-8b-code-base-1-2@sha256:9c30a00b764d5fe1d40416661113f6e63d512fb771c3d1a8a77241b0af422180
      name: granite-8b-code-base-1-2
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 355bcb7ffc7848746b42381765d505ef9f2898fd
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-code-base
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/granite-8b-code-instruct-1-2@sha256:ab2555e1e1b27056180d8b11a843d38275f917420ad78bbacb4e382614a31486
      name: granite-8b-code-instruct-1-2
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 1b531404e8652e28ef579ca65ae4109326fce4ca
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-code-instruct.git
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/knowledge-adapter-v3-1-2@sha256:37b2f9c829483415d04e8a3612ed07a713c9af753ae96e26a24fae59c8d9f785
      name: knowledge-adapter-v3-1-2
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: e40a624497a42dff6d409498f5a0b5bac773998e
          url: https://gitlab.com/redhat/rhel-ai/models/knowledge-adapter-v3
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/mixtral-8x7b-instruct-v0-1-1-2@sha256:481be8f9f7088b04389dcaa5d7851ceb34210570a6c431b03df9223636ea650a
      name: mixtral-8x7b-instruct-v0-1-1-2
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 074a831d67fd30a5404a12167e3ca61efbc6f798
          url: https://gitlab.com/redhat/rhel-ai/models/mixtral-8x7b-instruct-v0-1
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/prometheus-8x7b-v2-0-1-2@sha256:727a9841565abd151a20bd69934ddf6a59ecb8a17eea6f04e21515ee3613f652
      name: prometheus-8x7b-v2-0-1-2
      source:
        git:
          revision: 7e6141defe393df5c69b0926d0207558799da9e4
          url: https://gitlab.com/redhat/rhel-ai/models/prometheus-8x7b-v2-0
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-2/skills-adapter-v3-1-2@sha256:5236eefd39aa7be109d86e31dd79ab659811f61093cb313c13dc76f39a24e898
      name: skills-adapter-v3-1-2
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 03d3ce5db61b38d9fc70f54f7ef3c6242e9f4366
          url: https://gitlab.com/redhat/rhel-ai/models/skills-adapter-v3
