---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: rhel-ai-team
  name: nvidia-bootc-1-4-0
  namespace: rhel-ai-tenant
spec:
  releasePlan: nvidia-bootc-prod-1-4
  snapshot: nvidia-bootc-1-4-t7hnr
  data:
    mapping:
      defaults:
        tags:
          - "1.4.0"
