---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: granite-8b-code-base-1-1-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: models
  artifacts: {}
  components:
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models/granite-8b-code-base@sha256:30c14f55cb3b1bdf00cb99f69be0a818b2127a2c9764c70556c2873c9c5dd8a0
      name: granite-8b-code-base
      source:
        git:
          revision: ae75916af35435450beb8a2c22e33256dffa740b
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-code-base
