apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  finally:
    - name: slack-webhook-notification
      params:
        - name: message
          value: $(params.slack-message)
        - name: secret-name
          value: slack-webhook
        - name: key-name
          value: rhel-ai-notification
      taskRef:
        params:
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-slack-webhook-notification:0.1@sha256:4e68fe2225debc256d403b828ed358345bb56d03327b46d55cb6c42911375750
          - name: name
            value: slack-webhook-notification
          - name: kind
            value: Task
        resolver: bundles
      when:
        - input: $(tasks.status)
          operator: in
          values: ["Completed", "Succeeded"]
        - input: $(params.send-slack-notification)
          operator: in
          values: ["true"]
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - name: image-type
      description: Image type to build
      type: string
      default: ""
    - description: config.toml file to pass to BIB
      default: ""
      type: string
      name: config-toml
    - description: path to bib yaml file
      default: "bib.yaml"
      name: bib-file
      type: string
    - default: .
      description:
        Path to the source code of an application's component from where
        to build image.
      name: path-context
      type: string
    - default: Dockerfile
      description:
        Path to the Dockerfile inside the context specified by parameter
        path-context
      name: dockerfile
      type: string
    - default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "true"
      description: Skip optional checks, set false if you want to run optional checks
      name: skip-optional
      type: string
    - default: "false"
      description: Execute the build with network isolation
      name: hermetic
      type: string
    - default: ""
      description: Build dependencies to be prefetched by Cachi2
      name: prefetch-input
      type: string
    - default: "false"
      description: Java build
      name: java
      type: string
    - default: ""
      description:
        Image tag expiration time, time values could be something like
        1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
    - name: send-slack-notification
      default: "false"
      description: Send slack notification on completed build
    - name: slack-message
      description: Message to be sent
      type: string
      default: ""
    - name: additional-tags
      description: Additional tags to apply to the built image
      type: array
      default: []
    - name: build-platforms
      description: List of platforms to build the disk images on. The available
        set of values is determined by the configuration of the multi-platform-controller.
      type: array
      default:
        - linux-root/amd64
  results:
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    - description: ""
      name: IMAGE_URL
      value: $(tasks.build-image-index.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.build-image-index.results.IMAGE_DIGEST)
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)
        - name: rebuild
          value: $(params.rebuild)
        - name: skip-checks
          value: $(params.skip-checks)
        - name: skip-optional
          value: $(params.skip-optional)
        - name: pipelinerun-name
          value: $(context.pipelineRun.name)
        - name: pipelinerun-uid
          value: $(context.pipelineRun.uid)
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:1d8221c84f91b923d89de50bf16481ea729e3b68ea04a9a7cbe8485ddbb27ee6
          - name: kind
            value: task
        resolver: bundles
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:d35e5d501cb5f5f88369511f76249857cb5ac30250e1dcf086939321964ff6b9
          - name: kind
            value: task
      when:
        - input: "$(tasks.init.results.build)"
          operator: in
          values:
          - 'true'
      runAfter:
        - init
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.revision)"
        - name: ociStorage
          value: "$(params.output-image).git"
        - name: ociArtifactExpiresAfter
          value: "$(params.image-expires-after)"
        - name: enableSymlinkCheck
          value: false
      workspaces:
        - name: basic-auth
          workspace: git-auth
    - name: prefetch-dependencies
      params:
        - name: input
          value: $(params.prefetch-input)
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
        - name: ociStorage
          value: $(params.output-image).prefetch
        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)
        - name: dev-package-managers
          value: "true"
      runAfter:
        - clone-repository
      taskRef:
        params:
          - name: name
            value: prefetch-dependencies-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-prefetch-dependencies-oci-ta:0.2@sha256:092491ac0f6e1009d10c58a1319d1029371bf637cc1293cceba53c6da5314ed1
          - name: kind
            value: task
        resolver: bundles
      workspaces:
        - name: git-basic-auth
          workspace: git-auth
        - name: netrc
          workspace: netrc
    - name: build-vm-image
      timeout: "3h0m00s"
      matrix:
        params:
          - name: PLATFORM
            value:
              - $(params.build-platforms)
      params:
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
        - name: CONTEXT
          value: $(params.path-context)
        - name: IMAGE_TYPE
          value: $(params.image-type)
        - name: PREFETCH_INPUT
          value: $(params.prefetch-input)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: OUTPUT_IMAGE
          value: $(params.output-image)
        - name: CONFIG_TOML_FILE
          value: $(params.config-toml)
        - name: BIB_CONFIG_FILE
          value: $(params.bib-file)
        - name: IMAGE_APPEND_PLATFORM
          value: "true"
      runAfter:
        - prefetch-dependencies
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: build-vm-image
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-vm-image:0.1@sha256:39298d42e92fdd8e88e84ea40f5d88b529c13fccb762796fe38c77bc641d4d26
          - name: kind
            value: task
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
    - name: build-image-index
      timeout: "3h0m00s"
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: IMAGES
          value: $(tasks.build-vm-image.results.IMAGE_REFERENCE[*])
      runAfter:
        - build-vm-image
      taskRef:
        params:
          - name: name
            value: build-image-manifest
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-build-image-manifest:0.1@sha256:b4e7822a51a241e46b34ba9595b5c0028d6b1de628502e1592a3e7bfc8f6d475
          - name: kind
            value: task
        resolver: bundles
    - name: apply-tags
      params:
        - name: IMAGE_URL
          value: $(tasks.build-image-index.results.IMAGE_URL)
        - name: IMAGE_DIGEST
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)
        - name: ADDITIONAL_TAGS
          value:
            - $(params.additional-tags[*])
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: apply-tags
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.2@sha256:517a51e260c0b59654a9d7b842e1ab07d76bce15ca7ce9c8fd2489a19be6463d
          - name: kind
            value: task
        resolver: bundles
    - name: sast-shell-check
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: sast-shell-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-shell-check-oci-ta:0.1@sha256:bf7bdde00b7212f730c1356672290af6f38d070da2c8a316987b5c32fd49e0b9
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: sast-unicode-check
      params:
        - name: image-digest
          value: $(tasks.build-image-index.results.IMAGE_DIGEST)
        - name: image-url
          value: $(tasks.build-image-index.results.IMAGE_URL)
        - name: SOURCE_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.SOURCE_ARTIFACT)
        - name: CACHI2_ARTIFACT
          value: $(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)
      runAfter:
        - build-image-index
      taskRef:
        params:
          - name: name
            value: sast-unicode-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-unicode-check-oci-ta:0.3@sha256:a2bde66f6b4164620298c7d709b8f08515409404000fa1dc2260d2508b135651
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
  workspaces:
    - name: git-auth
      optional: true
    - name: netrc
      optional: true
