apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: copy-pipeline
spec:
  params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like 1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
    - name: aws-secret-name
      description: Name of a secret which will be made available to the build as an Authorization header
      type: string
      default: "also-to-be-defined-in-task"
    - name: bearer-token-secret-name
      description: Name of a secret which will be made available to the build as an Authorization header
      type: string
      default: "does-not-exist"
    - default: "false"
      description: Skip checks against built image
      name: skip-checks
      type: string
    - default: "false"
      description: Force rebuild image
      name: rebuild
      type: string
    - description: "OCI copy file"
      name: oci_copy_file
      type: string
        
  results:
    - description: ""
      name: IMAGE_URL
      value: $(tasks.oci-copy.results.IMAGE_URL)
    - description: ""
      name: IMAGE_DIGEST
      value: $(tasks.oci-copy.results.IMAGE_DIGEST)
    - description: ""
      name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - description: ""
      name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
  tasks:
    - name: init
      params:
        - name: image-url
          value: $(params.output-image)
        - name: rebuild
          value: $(params.rebuild)
        - name: skip-checks
          value: $(params.skip-checks)
      taskRef:
        params:
          - name: name
            value: init
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init@sha256:f239f38bba3a8351c8cb0980fde8e2ee477ded7200178b0f45175e4006ff1dca 
          - name: kind
            value: task
        resolver: bundles
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.revision)
        - name: depth
          value: 10
        - name: enableSymlinkCheck
          value: false
        - name: ociStorage
          value: $(params.output-image).git
        - name: ociArtifactExpiresAfter
          value: $(params.image-expires-after)            
      runAfter:
        - init
      taskRef:
        params:
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:d1e63ec00bed1c9f0f571fa76b4da570be49a7c255c610544a461495230ba1b1
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
      workspaces:
        - name: basic-auth
          workspace: git-auth
    - name: oci-copy
      timeout: "4h0m00s"
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: OCI_COPY_FILE
          value: $(params.oci_copy_file)
        - name: IMAGE_EXPIRES_AFTER
          value: $(params.image-expires-after)
        - name: COMMIT_SHA
          value: $(tasks.clone-repository.results.commit)
        - name: BEARER_TOKEN_SECRET_NAME
          value: $(params.bearer-token-secret-name)
        - name: AWS_SECRET_NAME
          value: $(params.aws-secret-name)
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      runAfter:
        - clone-repository
      taskRef:
        params:
          - name: name
            value: oci-copy-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-oci-copy-oci-ta:0.1@sha256:bd2dc219e45dc831ffa36b27a7afce0a4dfdc6b48347a517f5e5bc1284b507cd
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(tasks.init.results.build)
          operator: in
          values:
            - "true"
    - name: sast-snyk-check
      timeout: 2h
      params:
        - name: image-url
          value: $(tasks.oci-copy.results.IMAGE_URL)
        - name: image-digest
          value: $(tasks.oci-copy.results.IMAGE_DIGEST)
        - name: SOURCE_ARTIFACT
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
      runAfter:
        - oci-copy
      taskRef:
        params:
          - name: name
            value: sast-snyk-check-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-sast-snyk-check-oci-ta:0.3@sha256:6d232347739a0366dcfc4e40afbcb5d1937dd3fea8952afb1bd6a4b0c5d1c1f5            
          - name: kind
            value: task
        resolver: bundles
      when:
        - input: $(params.skip-checks)
          operator: in
          values:
            - "false"
    - name: apply-tags
      params:
        - name: IMAGE
          value: $(tasks.oci-copy.results.IMAGE_URL)
      runAfter:
        - oci-copy
      taskRef:
        params:
          - name: name
            value: apply-tags
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-apply-tags:0.1@sha256:0767c115d4ba4854d106c9cdfabdc1f1298bc2742a3fea4fefbac4b9c5873d6e
          - name: kind
            value: task
        resolver: bundles
  workspaces:
    - name: git-auth
      optional: true

