kind: Pipeline
apiVersion: tekton.dev/v1
metadata:
  name: rhaiis-tests
spec:
  params:
    - name: amdgpu-base-version
      default: "6.4.4"
      description: AMD GPU base version for repository URL
    - name: amdgpu-version
      default: "6.4.60404"
      description: AMD GPU installer version
    - name: architecture
      default: "x86_64"
      description: One of x86_64, aarch64
    - name: container-name
      default: "rhaii"
      description: Name of the RHAIIS podman container to monitor (rhaii for 3.4+, rhaiis for earlier versions)
    - name: inference-server-fallback-image
      default: ""
      description: >
        Fallback inference server image to use when testing model-opt and the
        inference server is not in the SNAPSHOT.
    - name: cuda-compat-version
      default: "12-9"
      description: |
        Version of the cuda-compat package to install.
        E.g. drivers 570 come with CUDA 12.8, cuda-compat-12-9 brings CUDA 12.9 compatibility for drivers 570.
        https://docs.nvidia.com/deploy/cuda-compatibility/forward-compatibility.html
    - name: debug
      default: "false"
    - name: model-names
      type: array
      default:
        - "ibm-granite/granite-3.3-2b-instruct"
      description: List of models to test
    - name: nvidia-driver-version
      default: "570"
      description: NVIDIA driver version to install, 570 for CUDA 12.8
    - name: pull-secret-names
      type: array
      default:
        - "rhaiis-pull"
      description: List of pull secret names for image authentication
    - name: SNAPSHOT
      description: |
        Snapshot of the application
        Example:
        {"components":[{"containerImage":"quay.io/redhat-user-workloads/ai-tenant/rhaiis/rhaiis-spyre-ubi9@sha256:2092e4808e9636356f408fc1f86ae2000eef659b87b0bcb01ad95512845990a2","name":"rhaiis-spyre-ubi9","source":{"git":{"context":".","dockerfileUrl":"Containerfile.spyre-ubi9","revision":"a73cf5e99dcbce3cb34491046918b5103e13247e","url":"https://gitlab.com/redhat/rhel-ai/rhaiis/containers"}}},{"containerImage":"quay.io/redhat-user-workloads/ai-tenant/rhaiis/rhaiis-tpu-ubi9@sha256:6ce221fe950283193979ffbc4aea879ea009f2dd6ee0ec402ab15c6d6702ac04","name":"rhaiis-tpu-ubi9","source":{"git":{"context":".","dockerfileUrl":"Containerfile.tpu-ubi9","revision":"a73cf5e99dcbce3cb34491046918b5103e13247e","url":"https://gitlab.com/redhat/rhel-ai/rhaiis/containers"}}},{"containerImage":"quay.io/redhat-user-workloads/ai-tenant/rhaiis/rhaiis-cuda-ubi9@sha256:ad756c01ec99a99cc7d93401c41b8d92ca96fb1ab7c5262919d818f2be4f3768","name":"rhaiis-cuda-ubi9","source":{"git":{"context":".","dockerfileUrl":"Containerfile.cuda-ubi9","revision":"a73cf5e99dcbce3cb34491046918b5103e13247e","url":"https://gitlab.com/redhat/rhel-ai/rhaiis/containers"}}},{"containerImage":"quay.io/redhat-user-workloads/ai-tenant/rhaiis/rhaiis-model-opt-cuda-ubi9@sha256:7dfd1ba91765aa8401e498c2ff651460f4c055d177b65c6b893bd587ba21a0f7","name":"rhaiis-model-opt-cuda-ubi9","source":{"git":{"context":".","dockerfileUrl":"Containerfile.model-opt.cuda-ubi9","revision":"a73cf5e99dcbce3cb34491046918b5103e13247e","url":"https://gitlab.com/redhat/rhel-ai/rhaiis/containers"}}},{"containerImage":"quay.io/redhat-user-workloads/ai-tenant/rhaiis/rhaiis-rocm-ubi9@sha256:8624e2a5086cf1303b59154a817f60a3476d6ca48899261a2e477eb9e99ae781","name":"rhaiis-rocm-ubi9","source":{"git":{"revision":"a73cf5e99dcbce3cb34491046918b5103e13247e","url":"https://gitlab.com/redhat/rhel-ai/rhaiis/containers"}}}]}
    - name: spot
      default: "true"
      description: Whether to use spot instances for AWS and Azure
  results:
    - name: container-image
      value: $(tasks.create-configuration.results.container-image)
    - name: inference-server-image
      value: $(tasks.create-configuration.results.inference-server-image)

  tasks:
    - name: create-configuration
      description: Placeholder task that prints the Snapshot and outputs standard TEST_OUTPUT
      params:
        - name: architecture
          value: $(params.architecture)
        - name: inference-server-fallback-image
          value: $(params.inference-server-fallback-image)
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/config-from-snapshot.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
    - name: create-vm-aws
      params:
        - name: arch
          value: "$(tasks.create-configuration.results.mapt-architecture)"
        - name: compute-sizes
          value: "$(tasks.create-configuration.results.vm-types)"
        - name: debug
          value: "true"
        - name: host-access-secret-name
          value: "mapt-rhel-$(context.pipelineRun.name)"          
        - name: id
          value: "$(context.pipelineRun.name)"
        - name: operation
          value: "create"
        - name: ownerKind
          value: "PipelineRun"
        - name: ownerName
          value: "$(context.pipelineRun.name)"
        - name: ownerUid
          value: "$(context.pipelineRun.uid)"
        - name: secret-aws-credentials
          value: "aws-konflux-tests"
        - name: spot
          value: "$(params.spot)"
        - name: spot-eviction-tolerance
          value: "high"
        - name: spot-increase-rate
          value: "100"
        - name: tags
          value: "$(tasks.create-configuration.results.base-tags),mapt-id=$(context.pipelineRun.name),mapt-type=rhel,pipeline-run-url=$(tasks.create-configuration.results.pipeline-run-url-prefix)$(context.pipelineRun.name)"
        - name: version
          value: "9.6" # RHEL version
      runAfter:
        - create-configuration
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/redhat-developer/mapt"
          # todo configure renovate to update this
          - name: revision
            value: "v0.14.0"
          - name: pathInRepo
            value: "tkn/infra-aws-rhel.yaml"
      when:
        - input: $(tasks.create-configuration.results.cloud-provider)
          operator: in
          values: ["aws"]
    - name: create-vm-azure
      params:
        - name: arch
          value: "$(tasks.create-configuration.results.mapt-architecture)"
        - name: compute-sizes
          value: "$(tasks.create-configuration.results.vm-types)"
        - name: debug
          value: "true"
        - name: id
          value: "$(context.pipelineRun.name)"
        - name: host-access-secret-name
          value: "mapt-rhel-$(context.pipelineRun.name)"
        - name: location
          value: "eastus"
        - name: operation
          value: "create"
        - name: ownerKind
          value: "PipelineRun"
        - name: ownerName
          value: "$(context.pipelineRun.name)"
        - name: ownerUid
          value: "$(context.pipelineRun.uid)"
        - name: secret-az-credentials
          value: "secret-az-credentials"
        - name: spot
          value: "$(params.spot)"
        - name: spot-eviction-tolerance
          value: "high"
        - name: spot-increase-rate
          value: "100"
        - name: tags
          value: "$(tasks.create-configuration.results.base-tags),mapt-id=$(context.pipelineRun.name),mapt-type=rhel,pipeline-run-url=$(tasks.create-configuration.results.pipeline-run-url-prefix)$(context.pipelineRun.name)"
        - name: version
          value: "9.6" # RHEL version
      runAfter:
        - create-configuration
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/redhat-developer/mapt"
          - name: revision
            value: "v0.14.1"
          - name: pathInRepo
            value: "tkn/infra-azure-rhel.yaml"
      when:
        - input: $(tasks.create-configuration.results.cloud-provider)
          operator: in
          values: ["azure"]
    - name: configure-vm-cuda
      retries: 1
      params:
        - name: cuda-compat-version
          value: "$(params.cuda-compat-version)"
        - name: host-access-secret-name
          value: "$(tasks.create-vm-aws.results.host-access-secret)"
        - name: nvidia-driver-version
          value: "$(params.nvidia-driver-version)"
      runAfter:
        - create-vm-aws
        - create-vm-azure
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/configure-vm-cuda.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
      when:
        - input: $(tasks.create-configuration.results.variant)
          operator: in
          values: ["cuda-ubi9"]
    - name: configure-vm-cpu
      retries: 1
      params:
        - name: host-access-secret-name
          value: "$(tasks.create-vm-aws.results.host-access-secret)"
      runAfter:
        - create-vm-aws
        - create-vm-azure
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/configure-vm-cpu.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
      when:
        - input: $(tasks.create-configuration.results.variant)
          operator: in
          values: ["cpu-ubi9"]
    - name: configure-vm-neuron
      retries: 1
      params:
        - name: host-access-secret-name
          value: "$(tasks.create-vm-aws.results.host-access-secret)"
      runAfter:
        - create-vm-aws
        - create-vm-azure
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/configure-vm-neuron.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
      when:
        - input: $(tasks.create-configuration.results.variant)
          operator: in
          values: ["neuron-ubi9"]
    - name: configure-vm-gaudi
      retries: 1
      params:
        - name: host-access-secret-name
          value: "$(tasks.create-vm-aws.results.host-access-secret)"
      runAfter:
        - create-vm-aws
        - create-vm-azure
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/configure-vm-gaudi.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
      when:
        - input: $(tasks.create-configuration.results.variant)
          operator: in
          values: ["gaudi-ubi9"]
    - name: configure-vm-rocm
      retries: 1
      params:
        - name: amdgpu-base-version
          value: "$(params.amdgpu-base-version)"
        - name: amdgpu-version
          value: "$(params.amdgpu-version)"
        - name: host-access-secret-name
          value: "mapt-rhel-$(context.pipelineRun.name)"
      runAfter:
        - create-vm-aws
        - create-vm-azure
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/configure-vm-rocm.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
      when:
        - input: $(tasks.create-configuration.results.variant)
          operator: in
          values: ["rocm-ubi9"]
    - name: pull-images
      retries: 3
      params:
        - name: container-images
          value:
            - "$(tasks.create-configuration.results.inference-server-image)"
            - "$(tasks.create-configuration.results.model-opt-image)"
        - name: host-access-secret-name
          value: "mapt-rhel-$(context.pipelineRun.name)"
        - name: pull-secret-names
          value: ["$(params.pull-secret-names[*])"]
      runAfter:
        - configure-vm-cuda
        - configure-vm-cpu
        - configure-vm-gaudi
        - configure-vm-neuron
        - configure-vm-rocm
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/pull-image.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
    - name: download-models
      params:
        - name: model-names
          value: ["$(params.model-names[*])"]
        - name: host-access-secret-name
          value: "mapt-rhel-$(context.pipelineRun.name)"
      runAfter:
        - configure-vm-cuda
        - configure-vm-cpu
        - configure-vm-gaudi
        - configure-vm-neuron
        - configure-vm-rocm
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/download-model.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
    - name: test-model-opt-quantization
      params:
        - name: container-image
          value: "$(tasks.create-configuration.results.model-opt-image)"
        - name: host-access-secret-name
          value: "mapt-rhel-$(context.pipelineRun.name)"
        - name: model-names
          value: ["$(params.model-names[*])"]
        - name: git-url
          value: "https://gitlab.com/redhat/rhel-ai/konflux-data.git"
        - name: git-revision
          value: "main"
        - name: git-token-secret-name
          value: "pipelines-as-code-secret"
      runAfter:
        - pull-images
        - download-models
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test-model-opt-quantization.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
      when: # Runs model-opt quantization only when testing model-opt (non-empty model-opt-image)
        - input: $(tasks.create-configuration.results.model-opt-image)
          operator: notin
          values: [""]
    - name: test-inference
      params:
        - name: container-name
          value: "$(params.container-name)"
        - name: debug
          value: "$(params.debug)"
        - name: inference-server-image
          value: "$(tasks.create-configuration.results.inference-server-image)"
        - name: variant
          value: "$(tasks.create-configuration.results.variant)"
        - name: host-access-secret-name
          value: "mapt-rhel-$(context.pipelineRun.name)"
        - name: model-names
          value: ["$(params.model-names[*])"]
      runAfter:
        - pull-images
        - download-models
        - test-model-opt-quantization
      taskRef:
        resolver: git
        params:
          - name: org
            value: redhat
          - name: repo
            value: rhel-ai/konflux-data
          - name: scmType
            value: gitlab
          - name: serverURL
            value: https://gitlab.com
          - name: revision
            value: main
          - name: pathInRepo
            value: tasks/test-inference.yaml
          - name: token
            value: pipelines-as-code-secret
          - name: tokenKey
            value: password
  finally:
    - name: delete-vm-aws
      params:
        - name: id
          value: "$(context.pipelineRun.name)"
        - name: operation
          value: "destroy"
        - name: secret-aws-credentials
          value: "aws-konflux-tests"
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/redhat-developer/mapt"
          # TODO configure renovate to update this
          - name: revision
            value: "v0.14.0"
          - name: pathInRepo
            value: "tkn/infra-aws-rhel.yaml"
      when:
        - input: $(tasks.create-configuration.results.cloud-provider)
          operator: in
          values: ["aws"]
    - name: delete-vm-azure
      params:
        - name: id
          value: "$(context.pipelineRun.name)"
        - name: operation
          value: "destroy"
        - name: secret-az-credentials
          value: "secret-az-credentials"
      taskRef:
        resolver: git
        params:
          - name: url
            value: "https://github.com/redhat-developer/mapt"
          - name: revision
            value: "v0.14.1"
          - name: pathInRepo
            value: "tkn/infra-azure-rhel.yaml"
      when:
        - input: $(tasks.create-configuration.results.cloud-provider)
          operator: in
          values: ["azure"]
