---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: rhel-ai-team
  name: amd-azure-bootc-1-3-1-0
  namespace: rhel-ai-tenant
spec:
  releasePlan: amd-azure-bootc-prod-1-3
  snapshot: amd-azure-bootc-1-3-5kg9k
  data:
    mapping:
      defaults:
        tags:
          - "1.3.1"
