---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: nvidia-bootc-qcow2-disk-image-1-3-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: nvidia-bootc-1-3-qcow2-disk-image
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/nvidia-bootc-1-3-qcow2-disk-image/nvidia-bootc-1-3-qcow2-disk-image@sha256:80c0eafc75e9b6c00006996cd5bf6e2fa625687d7b2515e613a5b1ab09547f62
    name: nvidia-bootc-1-3-qcow2-disk-image
    source:
      git:
        revision: 8bfa6d04a95335a1f705a8b630b4f33ca7a8949d
        url: https://gitlab.com/redhat/rhel-ai/disk-images/nvidia-bootc
