---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: rhel-ai-team
  name: models-1-3-0
  namespace: rhel-ai-tenant
spec:
  releasePlan: models-1-3-prod
  snapshot: models-1-3-88lgn
  data:
    mapping:
      defaults:
        tags:
          - "1.3.0"
