---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: models-1-3-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: models-1-3
  artifacts: {}
  components:
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/granite-7b-redhat-lab-1-3@sha256:4b3c7ab2d67f403fb6d58990221b04ab0206210f19c2018c5de2d275f0c0d14e
      name: granite-7b-redhat-lab-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: e200b3f5bd9e621665f5e14cff8176cdb45ecf25
          url: https://gitlab.com/redhat/rhel-ai/models/granite-7b-redhat-lab
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/granite-7b-starter-1-3@sha256:f3cb714bf2e8592157723f88b33c91b82aa124bfd16f5c1d75de91a921159392
      name: granite-7b-starter-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: cfb27fd84f04f87d558c62aa2aa02e1547173ca3
          url: https://gitlab.com/redhat/rhel-ai/models/granite-7b-starter
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/granite-8b-code-base-1-3@sha256:2d6361dd05f220eb65f0a6dc6950aafb058881f79ac2a6748ed7c08c50264128
      name: granite-8b-code-base-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 355bcb7ffc7848746b42381765d505ef9f2898fd
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-code-base
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/granite-8b-code-instruct-1-3@sha256:3b04dfe5fcbd4bcdcd1d4185fb2645974104fb173b437efe4cea1f37518aefe5
      name: granite-8b-code-instruct-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 1b531404e8652e28ef579ca65ae4109326fce4ca
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-code-instruct.git
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/knowledge-adapter-v3-1-3@sha256:ef1608ec78d5e39655b505544c0f30a015a6c9cb7e2b2deffe394791f8c76c6f
      name: knowledge-adapter-v3-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: e40a624497a42dff6d409498f5a0b5bac773998e
          url: https://gitlab.com/redhat/rhel-ai/models/knowledge-adapter-v3
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/mixtral-8x7b-instruct-v0-1-1-3@sha256:bc08e466aa35352a621d0ad221c2e247ff9751f4cb6cffe00d5894ce6bfd3fd7
      name: mixtral-8x7b-instruct-v0-1-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 074a831d67fd30a5404a12167e3ca61efbc6f798
          url: https://gitlab.com/redhat/rhel-ai/models/mixtral-8x7b-instruct-v0-1
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/prometheus-8x7b-v2-0-1-3@sha256:9fcb49c230f6e73ff944377307bb83a05ae3ac20300af75e429151f4f8bf4285
      name: prometheus-8x7b-v2-0-1-3
      source:
        git:
          revision: 7e6141defe393df5c69b0926d0207558799da9e4
          url: https://gitlab.com/redhat/rhel-ai/models/prometheus-8x7b-v2-0
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/skills-adapter-v3-1-3@sha256:53dd11a762bb39fc33c15499891309f0cdc8dbfd02abf94c9c60aad643aca255
      name: skills-adapter-v3-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 03d3ce5db61b38d9fc70f54f7ef3c6242e9f4366
          url: https://gitlab.com/redhat/rhel-ai/models/skills-adapter-v3
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/granite-8b-lab-v1-1-3@sha256:38d9b93127665e2f12b6dbf30519320a47ca7843fa7b6316d1d86d7f4d82f96d
      name: granite-8b-lab-v1-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 10011d803aeae543f0b2776f17044c0aa47227a1
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-lab-v1
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/granite-8b-starter-v1-1-3@sha256:f9deaa56a93bb8480f48073c1e11b5feb30d1d9854861912e75db6e383b17613
      name: granite-8b-starter-v1-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 90ca2350e4772d69875dcf7af1222d0e5aa1b40a
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-starter-v1
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/models-1-3/granite-8b-lab-v2-preview-1-3@sha256:c3fc2b7efacc5aa1f3a6e49afacd950d6f8e4eb0db4b11045929522b90daff1a
      name: granite-8b-lab-v2-preview-1-3
      source:
        git:
          context: ./
          dockerfileUrl: Containerfile
          revision: 2af18bb22e169f596ff15cee77e8df477958879b
          url: https://gitlab.com/redhat/rhel-ai/models/granite-8b-lab-v2-preview
