---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: instructlab-nvidia-1-1-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: instructlab-nvidia-1-1
  artifacts: {}
  components:
    - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/instructlab-nvidia-1-1/instructlab-nvidia-1-1@sha256:5d336f408b890396c179160b4b9e3d21ff61f30b56d97155eeeca48ec7eeefe7
      name: instructlab-nvidia-1-1
      source:
        git:
          revision: 2eaad6c733becf9d60ceb1756d42f81641adddeb
          url: https://gitlab.com/redhat/rhel-ai/containers/instructlab-nvidia
