---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Snapshot
metadata:
  name: nvidia-bootc-raw-disk-image-1-2-0
  namespace: rhel-ai-tenant
  labels:
    release.appstudio.openshift.io/auto-release: "false"
spec:
  application: nvidia-bootc-1-2-raw-disk-image
  artifacts: {}
  components:
  - containerImage: quay.io/redhat-user-workloads/rhel-ai-tenant/nvidia-bootc-1-2-disk-images/nvidia-bootc-1-2-raw-disk-image@sha256:508ad5034f85b35fe8b4f3d24d4beb75b7651c7453f1bb1434b5cb98e84bf496
    name: nvidia-bootc-1-2-raw-disk-image
    source:
      git:
        revision: 4e2dd13d17b5a2f5175d2922b310f840f6f401bc
        url: https://gitlab.com/redhat/rhel-ai/disk-images/nvidia-bootc
