---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: rhel-ai-team
  name: nvidia-bootc-raw-disk-image-1-3-0
  namespace: rhel-ai-tenant
spec:
  releasePlan: nvidia-bootc-1-3-raw-disk-image-prod
  snapshot: nvidia-bootc-raw-disk-image-1-3-0
  data:
    mapping:
      defaults:
        tags:
          - "1.3.0"
